fix: deleting non-existent topic shouldn't raise KeyError
spulec/moto pull request #3285
Opened 2020-09-04 04:45 UTC by okeyokoro

deleting non-existent topic shouldn't raise KeyError

2020-09-04 08:57 UTC, bblommers requested changes
Hi @okeyokoro, thanks for your PR! Looks like the tests are failing: https://travis-ci.org/github/spulec/moto/jobs/724034950

2020-09-05 01:23 UTC, okeyokoro commented
@bblommers thanks for picking this up! tests pass now 🙂

2020-09-10 07:32 UTC, bblommers approved these changes
LGTM. Thanks @okeyokoro!

2020-09-10 07:32 UTC, merged

2020-09-10 08:09 UTC, bblommers commented
This is now part of moto >= 1.3.16.dev2