ApplicationAutoscaling: support autoscaling policies, deregister_scalable_target
spulec/moto pull request #3350
Opened 2020-09-30 22:40 UTC by jweite

Also, changes so same ClientError is returned for validation exceptions as AWS does.

2020-10-02 12:27 UTC, bblommers requested changes
Hey @jweite - left a few comments

2020-10-02 12:27 UTC, bblommers commented on tests/test_applicationautoscaling/test_applicationautoscaling.py
> +    pass
Unnecessary

2020-10-02 12:27 UTC, bblommers commented on tests/test_applicationautoscaling/test_applicationautoscaling.py
> +    pass
Unnecessary

2020-10-02 12:27 UTC, bblommers commented on moto/applicationautoscaling/models.py
> +            raise AWSValidationException(
Can we get a  unit test for this error scenario?

2020-10-02 12:27 UTC, bblommers commented on moto/applicationautoscaling/models.py
> +            raise AWSValidationException(
And this one as well

2020-10-02 12:27 UTC, bblommers commented on moto/applicationautoscaling/models.py
> +            raise AWSValidationException(
Same here

2020-10-29 20:39 UTC, jweite commented
Lost track of this one, sorry!  Made the requested changes and rebased to current master.

2020-10-30 15:21 UTC, bblommers approved these changes
LGTM. Thanks @jweite!

2020-10-30 15:21 UTC, merged

2020-10-30 21:04 UTC, bblommers commented
This is now part of moto >= 1.3.16.dev83