Py3: use unittest.mock instead of mock
spulec/moto pull request #3481
Opened 2020-11-18 10:33 UTC by singingwolfboy

2021-03-28 12:00 UTC, singingwolfboy commented
Could someone please review this pull request? I just rebased it.

2021-03-28 13:59 UTC, bblommers requested changes
Hi @singingwolfboy, thanks for this PR!
Would you mind moving the try-catches to `compat.py`? The file is already in place in both the moto and tests directory - having all compatibility imports in one place will make it easier to keep track of them.

Looks like the CI is failing at the moment btw, but I haven't looked into why. Let me know if you need a hand with that.

2021-03-28 13:59 UTC, bblommers commented on tests/test_packages/test_httpretty.py
> +
This import is unused, as far as I can tell

2021-03-29 14:12 UTC, bblommers requested changes
Nice @singingwolfboy - happy to merge once the build passes

2021-04-05 14:13 UTC, singingwolfboy commented
@bblommers I finally got the tests to pass! Can you check my code once again, to make sure that the changes I made are acceptable?

2021-04-06 08:25 UTC, bblommers commented
Thanks for getting the build fixed,  @singingwolfboy. 
The try-except brings back some painful memories of #3541, which (I think) fixed the same problem in PY2, introduced by `mock==4.0.3`. 

I'll merge this for now, and have a look later on to see if my patch can be reverted with this solution.

2021-04-06 08:25 UTC, bblommers approved these changes

2021-04-06 09:22 UTC, merged