[dynamodb2] Support include projection on indexes
spulec/moto pull request #3498
Opened 2020-11-24 16:23 UTC by garrettheel

Adds support for `INCLUDE` projections for DynamoDB indexes, per https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Projection.html

2020-11-24 17:04 UTC, qnordic approved these changes

2020-11-25 08:56 UTC, bblommers requested changes
Hi @garrettheel, thanks for the PR! Looks like the linter failed: https://travis-ci.org/github/spulec/moto/builds/745678034

Happy to merge once Travis is green.

2020-11-25 12:52 UTC, garrettheel commented
@bblommers apologies, CI took so long to begin that I lost track of this. I've pushed up a fix for the linter

2020-11-25 20:27 UTC, bblommers approved these changes
LGTM

2020-11-25 20:28 UTC, merged