Fix:SNS Create FIFO Topic
spulec/moto pull request #3533
Opened 2020-12-09 20:58 UTC by usmangani1

Fix:SNS Create FIFO Topic
https://github.com/localstack/localstack/issues/3336

2020-12-10 09:15 UTC, bblommers requested changes

2020-12-10 09:15 UTC, bblommers commented on moto/sns/models.py
> +                r"^[a-zA-Z0-9_.-]{1,256}$", name
This regex would allow something like `name.something.fifo`, which is not valid.
A better regex would probably be `^[a-zA-Z0-9_-]{1,256}.fifo$`

2020-12-10 09:15 UTC, bblommers commented on tests/test_sns/test_topics_boto3.py
> +
Can we add a negative test as well? Just to assert that the correct error is thrown when creating a FIFO-queue without `.fifo` suffic

2020-12-10 20:02 UTC, bblommers requested changes

2020-12-10 20:02 UTC, bblommers commented on moto/sns/models.py
> +            fails_constraints = not re.match(r"^[a-zA-Z0-9_.-]{1,256}fifo$", name)
Need to move the `.` inside the regex:
`r"^[a-zA-Z0-9_-]{1,256}\.fifo$"`

Should have said this earlier, but worth creating another test case that verifies that `queue.name.fifo` also throws an error. (That name would be considered valid with the current regex, but shouldn't be.)

2021-01-19 18:00 UTC, wellermiranda commented
💯 

Any chance do fix it?

2021-01-20 09:38 UTC, bblommers requested changes
Sorry for the delay @usmangani1, and thanks for making the changes.
Looks like there's one more test failing due to an NPE:
https://travis-ci.org/github/spulec/moto/jobs/748858407

Happy to merge once that's fixed

2021-01-26 15:04 UTC, bblommers approved these changes
LGTM - thanks @usmangani1!

2021-01-26 15:04 UTC, merged

2021-01-26 16:42 UTC, bblommers commented
This is now part of moto >= 1.3.16.dev220