Add validation to put_events
spulec/moto pull request #3579
Opened 2021-01-03 16:58 UTC by gruebel

Fixes #3384 

It is a quite interesting behaviour of the `put_events` endpoint, because each event is validated separately and the status is send back for all of them.

2021-01-09 13:39 UTC, bblommers requested changes
Hey @gruebel, would you mind splitting up the test scenarios in multiple methods? 
Would be good to also test a scenario with multiple events, some valid, some invalid.

2021-01-09 21:19 UTC, gruebel commented
I also removed the weird `test_rule_tagging_sad` test and added the correct way of testing them.

2021-01-10 15:20 UTC, bblommers requested changes
Looks like it's failing in Py2:
`AttributeError: 'module' object has no attribute 'JSONDecodeError'`

2021-01-10 17:55 UTC, gruebel commented
@bblommers is there actually a plan to drop Python 2 support at some point?

2021-01-11 09:41 UTC, bblommers commented
There's no plan yet, @gruebel. There's still a significant portion of people that are stuck with Py2, and we want to keep Moto available to them as long as possible.
Thanks for the PR!

2021-01-11 09:41 UTC, bblommers approved these changes

2021-01-11 09:41 UTC, merged