s3 metadata with dot fix
spulec/moto pull request #3581
Opened 2021-01-04 17:06 UTC by macnev2013

**fixed**
- s3 with meta keys not showing if contains dot in it.

Example: 
```
awslocal s3 mb s3://my-bucket
awslocal s3api put-object --bucket my-bucket --key my-key --metadata key-with.dot=123143123
awslocal s3api head-object --bucket my-bucket --key my-key
```

this PR will fix issue [localstack/issue/3423](https://github.com/localstack/localstack/issues/3423)

2021-01-05 02:00 UTC, macnev2013 commented
Hey @bblommers . Can you help me with this build. Looks like the build failure is unrelated to my changes.

2021-01-05 13:49 UTC, bblommers commented
It is unrelated, @macnev2013. Travis has been a bit unreliably lately. 
Will have a look at this PR the moment we get our CI sorted. 👍

2021-01-07 16:01 UTC, macnev2013 commented
Hey @bblommers, Any updates on this one? Waiting to have this fixed.

2021-01-08 15:31 UTC, bblommers requested changes
Hey @macnev2013, can you add a unit test for this? Happy to merge afterwards

2021-01-14 13:50 UTC, closed without merging