Functionality added to SES service
spulec/moto pull request #3670
Opened 2021-02-09 22:20 UTC by pinzon

This patch adds the functions test_render_template and update_template so the SES service.
Also adds validation to the function add_template.

Each new function has its corresponding test.

This should close issue localstack/localstack/issues/3466

2021-02-10 17:58 UTC, pinzon commented
Hi @bblommers sorry to bother you. Could you review my PR? 
Is there something else I should do? some tests failed but I don't think they have to do with my changes.
Thank you.

2021-02-11 14:41 UTC, bblommers requested changes
Thanks for the PR, @pinzon! I've left a few comments.
Looks like the build is failing as well, because of a Py2 issue: https://github.com/spulec/moto/pull/3670/checks?check_run_id=1872455785

2021-02-11 14:41 UTC, bblommers commented on tests/test_ses/test_ses_boto3.py
> +    assert True == result["RenderedTemplate"].__contains__("Subject: Greetings, John!")
Please use the should-flow for these assertions:
`template.should.contain(...)`

2021-02-11 14:41 UTC, bblommers commented on tests/test_ses/test_ses_boto3.py
> +    conn.test_render_template.when.called_with(**kwargs).should.throw(ClientError)
When testing error scenarios, we prefer to use pytest.raises, as that makes it easier to assert that the correct error was thrown:
```
with pytest.raises(ClientError) as ex:
  # something that fails
err  = ex.value.response["Error"]
err["Code"].should.equal("...")
err["Message"].should.equal("...")
```

2021-02-11 17:35 UTC, pinzon commented
Hi @bblommers, my last commit should fix that error and I changed the tests as requested.
Thank you for your help.

2021-02-11 18:31 UTC, bblommers approved these changes
LGTM. Thanks again @pinzon!

2021-02-11 18:31 UTC, merged