dynamodb: fix deleting last set element (w/attr name)
spulec/moto pull request #3708
Opened 2021-02-17 23:02 UTC by ikonst

2021-02-18 13:30 UTC, bblommers requested changes
Hi @ikonst, thanks for the PR!
Can you add a user-facing unit test as well, to make it explicit how an end user would run into this scenario? I'm guessing it's just a slightly modified variant of the `test_dynamodb.py::test_set_attribute_is_dropped_if_empty_after_update_expression` test

2021-02-18 15:30 UTC, ikonst commented
@bblommers Thanks for the pointer! Added.

2021-02-19 07:47 UTC, bblommers approved these changes
LGTM. Thanks again, @ikonst!

2021-02-19 07:47 UTC, merged

2021-02-19 08:38 UTC, bblommers commented
This is now part of moto >= 1.3.17.dev280