Fix unknown instance type
spulec/moto pull request #3710
Opened 2021-02-18 14:57 UTC by nuwang

This PR switches to the `describe_instance_types` API to populate `instance_types.json`, instead of using `www.ec2instances.info`. This fixes an issue where the `describe_instance_type_offerings` API call returns instances which are not listed in `instance_types.json`

ping @spulec @bblommers

2021-02-21 10:06 UTC, bblommers requested changes
Thanks for the PR, @nuwang! Makes sense, to get the data directly from AWS.
Please see my comments - happy to merge once that's addressed

2021-02-21 11:12 UTC, nuwang commented on scripts/get_instance_info.py
> +    for region in ["us-east-1"]:
Thanks for the catch! Fixed.

2021-02-21 17:44 UTC, bblommers commented on scripts/get_instance_info.py
> +    for region in ["us-east-1"]:
Doesn't use the regions-variable yet, @nuwang :)

2021-02-21 18:46 UTC, nuwang commented on scripts/get_instance_info.py
> +    for region in ["us-east-1"]:
@bblommers Oops! I had missed this one which I used while testing. Sorry about that.

2021-02-21 18:49 UTC, nuwang commented
One sec, am updating instance types from all regions.

2021-02-21 19:01 UTC, nuwang commented
All done.

2021-02-22 10:21 UTC, bblommers approved these changes
LGTM - thanks again @nuwang!

2021-02-22 10:21 UTC, merged

2021-02-22 11:17 UTC, bblommers commented
This is now part of moto >= 1.3.17.dev283

2021-02-22 12:05 UTC, nuwang commented
Thanks for the review and merge!