IAM - get_user() #3828
spulec/moto pull request #3829
Opened 2021-04-02 05:41 UTC by Jonx1000

- fixing issue where the get_user method does not return tags

Fixes #3828

Documentation:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.get_user

2021-04-02 08:43 UTC, bblommers requested changes
Hi @Jonx1000, thanks for the PR! 
Can you add a test for this, to verify it's returned correctly? Probably easiest to extend the existing 'tests/test_iam/test_iam.py::test_create_user_with_tags` with a `get_user` call

2021-04-02 08:43 UTC, bblommers commented on moto/iam/responses.py
> +            tags = iam_backend.tagger.list_tags_for_resource(user.arn).get("Tags", [])
Looks like the indentation is incorrect - it shouldn't be part of the `else` statement

2021-04-02 13:17 UTC, Jonx1000 commented
@bblommers thank you I removed it from the conditional.

2021-04-02 21:29 UTC, Jonx1000 commented
Thanks for pointing that out. I added some tests.

2021-04-03 09:38 UTC, bblommers approved these changes
LGTM!

2021-04-03 09:38 UTC, merged