Make it possible to customize the ACM cert validation wait time.
spulec/moto pull request #3843
Opened 2021-04-09 10:02 UTC by xiaket

We are using AWS lambda to create/delete the acm certificates and doing the validation via DNS, when writing unittest for these lambdas we'll have to wait 60 seconds. This PR make it possible to customize this wait time.

2021-04-09 10:14 UTC, bblommers requested changes
Hey @xiaket, thanks for the PR!
Would you mind adding a unit test for this? See this test for an example on how we test env vars in other services: https://github.com/spulec/moto/blob/d3ad9d66866413670c31f36d54e939647feedeb1/tests/test_stepfunctions/test_stepfunctions.py#L933

2021-04-09 10:14 UTC, bblommers commented on moto/acm/models.py
> +        wait = os.environ.get("MOTO_ACM_VALIDATION_WAIT", 60)
This should be moved into `moto/settings.py`, where all our env variables are stored

2021-04-09 13:33 UTC, bblommers commented on tests/test_acm/test_acm.py
> +    # After requesting a certificate, it should then auto-validate after 1 minute
Still need to use the SkipTest here, otherwise our ServerMode tests wil fail

2021-04-09 13:34 UTC, bblommers commented
Make sure that  you use `black==19.10b0` for linting, as later versions have a few bugs

2021-04-09 13:35 UTC, xiaket commented
> Make sure that you use `black==19.10b0` for linting, as later versions have a few bugs

Cheers mate, I'm having trouble with this. :)

2021-04-10 00:36 UTC, xiaket commented
Thanks @bblommers. I ended up not mocking the envvar directly but mocked the value from settings(because there's a cache somewhere that I cannot figure out). Hope it looks good now. Please let me know if you have any follow up suggestions/comments. I appreciate your help!

2021-04-10 07:13 UTC, bblommers approved these changes
LGTM @xiaket - thanks again!

2021-04-10 07:13 UTC, merged