Add support for DynamoDB Backup/Restore
spulec/moto pull request #3995
Opened 2021-06-08 09:28 UTC by bpandola

Basic support for the following endpoints has been implemented with full test coverage:
- create_backup
- delete_backup
- describe_backup
- list_backups
- restore_table_from_backup

Behavior and error messages verified against a real AWS backend.

2021-06-08 19:06 UTC, bpandola commented
@bblommers Looks like another flaky test... I see other PRs with the same failure (`FAILED tests/test_elbv2/test_elbv2.py::test_handle_listener_rules`).

I'll have a look to see if it's an easy fix.

2021-06-09 07:21 UTC, bblommers requested changes
Thanks for the PR @bpandola! Just one comment, but happy with how it looks overall.

I'll have a look at the failing test as well later today.

2021-06-09 07:21 UTC, bblommers commented on tests/test_dynamodb2/test_dynamodb.py
> +def test_source_and_restored_table_items_are_not_linked():
Can we extend this test a bit, to verify the behaviour for items created between backup-creation and restoring?
```
create_backup
add_items to original table
restore_backup
verify original has x items
verify backup only has y items
```

2021-06-10 06:05 UTC, bblommers approved these changes
LGTM!

2021-06-10 06:05 UTC, merged