Add functionality SetIdentitiMailFromDomain, GetIdentityMailFromDomai…
spulec/moto pull request #4075
Opened 2021-07-18 16:38 UTC by usmangani1

Add functionality SetIdentitiMailFromDomain, GetIdentityMailFromDomainAttributes

2021-07-24 10:31 UTC, bblommers requested changes

2021-07-24 10:31 UTC, bblommers commented on moto/ses/models.py
> +            raise IdentityDoesNotExist(identity)
This will need a unit test

2021-07-24 10:31 UTC, bblommers commented on tests/test_ses/test_ses_boto3.py
> +    response = conn.get_identity_mail_from_domain_attributes(Identites=["domain1.com"])
Typo - 'Identities'

2021-07-24 10:31 UTC, bblommers commented on tests/test_ses/test_ses_boto3.py
> +    assert "MailFromDomainAttributes" in response
We know exactly the response format, so this should be more explicit - i.e., create the exact same dict and assert equality

2021-07-24 10:31 UTC, bblommers commented on tests/test_ses/test_ses_boto3.py
> +    response = conn.get_identity_mail_from_domain_attributes(Identites=["domain1.com"])
Can we get a few more calls here, and verify the correct behaviour response for various invocations:
 - get_identity_mail_from_domain_attributes before setting anything
 - get_identity_mail_from_domain_attributes(Identities=None) (after calling set_identity_mail_from_domain)
 - get_identity_mail_from_domain_attributes(Identities=[]) (after calling set_identity_mail_from_domain)

2021-11-12 11:12 UTC, krewenki commented
@usmangani1 Have you made any further progress on this?  I'm hitting issues related to this in localstack:

```
Aws\Ses\Exception\SesException: Error executing "GetIdentityDkimAttributes"
```

2022-02-09 18:20 UTC, closed without merging