WIP: Added PrefixList
spulec/moto pull request #4169
Opened 2021-08-12 17:04 UTC by monty16597

## Added
- Support for `PrefixList` and `ManagedPrefixList`.
- API `CreateManagedPrefixList`
- API `DescribeManagedPrefixLists`
- API `GetManagedPrefixListEntries`
- API `DeleteManagedPrefixList`
- API `DescribePrefixLists`

## Tested with
- Terraform
```terraform
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_vpc_endpoint" "s3" {
  vpc_id       = aws_vpc.main.id
  service_name = "com.amazonaws.us-west-2.s3"
}

resource "aws_vpc_endpoint" "s32" {
  vpc_id       = aws_vpc.main.id
  service_name = "com.amazonaws.us-west-2.s3"

  tags = {
    Environment = "test"
  }
}

resource "aws_subnet" "main" {
  vpc_id     = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"

  tags = {
    Name = "Main"
  }
}

resource "aws_vpc_endpoint" "ec2" {
  vpc_id            = aws_vpc.main.id
  service_name      = "com.amazonaws.us-west-2.ec2"
  vpc_endpoint_type = "Interface"
  subnet_ids = [aws_subnet.main.id]

  security_group_ids = [
    "sg-kj1h2i3112",
  ]

  private_dns_enabled = true
}
```

2021-08-13 05:06 UTC, bblommers requested changes
Hi @monty16597, thanks for the PR!
Can you add the new TF tests that will pass with this change to the `terraform-tests.success.txt` please?

2021-08-13 05:06 UTC, bblommers commented on moto/ec2/utils.py
> +def generate_vpc_end_point_id(vpc_id):
This doesn't seem to be used anywhere in this PR?

2021-08-13 05:06 UTC, bblommers commented on terraform.tfstate
> +{
This file shouldn't be part of Moto

2021-08-13 06:20 UTC, monty16597 commented
Hey @bblommers ,
This PR is still in progress, I accidentally removed WIP from the head. I will update it once we are ready to merge.

2021-08-13 06:33 UTC, bblommers commented
No worries @monty16597. I'll mark it as a draft then, to prevent accidental merges.

2021-08-13 06:53 UTC, monty16597 commented
Sounds Good, @bblommers  Thanks.

2021-08-14 14:58 UTC, monty16597 commented
Hello @bblommers ,
We are ready to merge the PR.

2021-08-14 15:30 UTC, bblommers approved these changes
Nice one - thanks @monty16597!

2021-08-14 15:31 UTC, merged