Fixed SourceGroup implementation in SG.
spulec/moto pull request #4239
Opened 2021-08-28 16:33 UTC by monty16597

# Improvements
- Improved SourceGroup implementation in SG.
- Fixed `AuthorizeSecurityGroupEgress` and `AuthorizeSecurityGroupIngress` response.
# Terraform Tests
- `TestAccAWSSecurityGroup_egressWithPrefixList`
- `TestAccAWSSecurityGroup_ingressWithPrefixList`
- `TestAccAWSSecurityGroup_ruleGathering`

2021-08-28 19:23 UTC, monty16597 commented
@bblommers Can you help me with the Response Tests?

2021-09-02 15:48 UTC, monty16597 commented
Hey @bblommers @whummer ,
We are ready to merge this PR.

2021-09-04 06:54 UTC, monty16597 commented
Hello @bblommers , Please let me know if anything is needed.

2021-09-04 08:37 UTC, bblommers requested changes
Apologies for the delay @monty16597 - please see my comments

2021-09-04 08:37 UTC, bblommers commented on moto/ec2/models.py
> +        prefix_list_ids=[],
Default arguments should always be None, IMO, as having a list as default can lead to really tricky bugs.
(https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments if you want a clear/concise summary of what can go wrong)

2021-09-04 08:37 UTC, bblommers commented on moto/ec2/models.py
> +        ip_ranges = [item for item in self.ip_ranges if item not in other.ip_ranges]
Should we use `set.symmetric_difference()` here to guarantee equality? 
Using the current comparison, the following scenario would still pass, if I'm not mistaken:
```
self.ip_ranges = [{"CidrIp": "0.0.0.0/0"}]
other.ip_ranges = [{"CidrIp": "1.1.1.1/0"}]
```

2021-09-04 08:37 UTC, bblommers commented on moto/ec2/models.py
> +        source_groups=[],
Same issue with the default arg

2021-09-04 08:37 UTC, bblommers commented on moto/ec2/models.py
> +        source_groups=[],
Same issue with the default arg

2021-09-04 08:37 UTC, bblommers commented on moto/ec2/models.py
> +        source_groups=[],
Same issue with the default arg

2021-09-04 08:37 UTC, bblommers commented on moto/ec2/models.py
> +        source_groups=[],
Same issue with the default arg

2021-09-04 13:46 UTC, monty16597 commented
@bblommers, I have updated the changes.

2021-09-04 15:14 UTC, monty16597 commented
Also, @bblommers , I wanted to ask if we do support `EC2-classic`, AWS is no more supporting those features, So every time we create SecurityGroup without a `VPC_ID` AWS will consider the default `VPC` for the SG. So wonder if we can do that the same. Any thought?

2021-09-04 16:07 UTC, bblommers commented
> 
> 
> Also, @bblommers , I wanted to ask if we do support `EC2-classic`, AWS is no more supporting those features, So every time we create SecurityGroup without a `VPC_ID` AWS will consider the default `VPC` for the SG. So wonder if we can do that the same. Any thought?

There is still a grace period for EC2-classic users, afaik, but there can't be that many users, it doesn't make sense to support that behaviour as our default. So creating SG's in the default VPC sounds good to me.

I'll merge this for now, as it's getting quite big already, but if you want to implement that in a future PR, that would be very welcome 👍

2021-09-04 16:08 UTC, bblommers approved these changes
LGTM! Thanks for the PR @monty16597

2021-09-04 16:08 UTC, merged