[WIP] feat: Adding validation to Cloudformation to reject same template_body
spulec/moto pull request #4351
Opened 2021-09-26 16:38 UTC by teddylear

feat: Adding validation to Cloudformation to reject same template_body and parameters

First PR to moto, please let me know if I'm missing anything or if anything should be changed. 

Addresses #4157

2021-09-27 10:11 UTC, bblommers requested changes
Hi @teddylear, thanks for the PR!
Would you mind extending the test, and call the `update_stack`-method with updated parameters at the end?
There's no need to verify that the update-method itself works as expected, that hasn't changed - just to verify that the error will not be thrown with different params.

2021-09-27 10:11 UTC, bblommers commented on tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
> +    assert exp_err.get("Message") == f"Stack [{name}] already exists"
```suggestion
    exp_err.get("Code").should.equal("ValidationError")
    exp_err.get("Message").should.equal(f"Stack [{name}] already exists")
```
This is more readable IMO

2021-09-27 23:39 UTC, teddylear commented on tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
> +    assert exp_err.get("Message") == f"Stack [{name}] already exists"
Agreed, updated to match this.

2021-09-27 23:40 UTC, teddylear commented
@bblommers 
Updated the test to call update stack with new parameters. Please let me know if there's anything else I should update.

2021-09-28 20:35 UTC, bblommers approved these changes
LGTM! Thanks for the PR @teddylear

2021-09-28 20:35 UTC, merged