Fix publishing to fifo sns->sqs subscription
spulec/moto pull request #4738
Opened 2022-01-05 13:46 UTC by sindrig

This closes #4737

2022-01-05 14:06 UTC, sindrig commented
Accidentally left an unused import in there. Removed in [b309487ed484970c01c2a6c355ddf8da22ca2274](https://github.com/spulec/moto/pull/4738/commits/b309487ed484970c01c2a6c355ddf8da22ca2274) and will need approval again

2022-01-05 16:08 UTC, bblommers requested changes

2022-01-05 16:08 UTC, bblommers commented on tests/test_sns/test_publishing_boto3.py
> +        topic.publish(Message="message", MessageGroupId="message_group_id")
Same here

2022-01-05 16:17 UTC, sindrig commented on tests/test_sns/test_publishing_boto3.py
> +    with pytest.raises(ClientError):
Yep, added in https://github.com/spulec/moto/pull/4738/commits/e7859eb958dcee4f5be082dd5f7ab4fb4706b6a0

2022-01-05 16:17 UTC, sindrig commented on tests/test_sns/test_publishing_boto3.py
> +        topic.publish(Message="message", MessageGroupId="message_group_id")
Ditto

2022-01-05 16:18 UTC, sindrig commented on tests/test_sns/test_publishing_boto3.py
> +    with pytest.raises(ClientError):
LMK if you prefer introspecting the thrown exception as opposed to `pytest.raises(match=...)`

2022-01-05 17:47 UTC, bblommers commented on tests/test_sns/test_publishing_boto3.py
> +    with pytest.raises(ClientError):
No, this is fine - as long as we know the correct error was raised. Thanks!

2022-01-05 17:48 UTC, bblommers commented
Looks like some other tests are still failing with these changes

2022-01-06 14:37 UTC, sindrig commented
Should be good now :pray:

2022-01-06 16:04 UTC, bblommers approved these changes
LGTM! Thanks for the PR and fixing this @sindrig

2022-01-06 16:04 UTC, merged