feat: add support for filtering by tags in describe_managed_prefix_lists
spulec/moto pull request #4747
Opened 2022-01-11 19:19 UTC by Neki

This PR adds support for filtering by tags (instead of ignoring the tag filter and returning all results) during calls to `describe_managed_prefix_lists` (EC2 client).

The test added in this PR doesn't pass without the associated change.

I made the minimal change that would allow me to use moto to test a project I'm working on. Please let met know if that approach is OK!

2022-01-11 20:13 UTC, Neki commented
The test failures seem unrelated. Please let me know if there's something I need to do to make them pass.

2022-01-12 22:40 UTC, bblommers requested changes
Hi @Neki, thanks for the PR! Would you mind merging with master? That should fix the CI - happy to merge once all the tests pass

2022-01-13 09:22 UTC, Neki commented
Thanks, I rebased this MR against the latest master, tests are green now :heavy_check_mark:

2022-01-13 12:40 UTC, bblommers approved these changes
Nice one - thanks again @Neki!

2022-01-13 12:41 UTC, merged