ec2: Add GpuInfo to describe_instance_types
spulec/moto pull request #4828
Opened 2022-02-04 12:03 UTC by edisongustavo

## Testing

I have inspected the return result and saw that the instance types that should have Gpus do have the correct values.

For example, looking at the entry for `g4ad.8xlarge`:

```
{'GpuInfo': {'Gpus': [{'Count': 2,
                       'Manufacturer': 'AMD',
                       'MemoryInfo': {'SizeInMiB': 8192},
                       'Name': 'Radeon Pro V520'}],
             'TotalGpuMemoryInMiB': 16384},
 'InstanceStorageInfo': {'TotalSizeInGB': 1200},
 'InstanceType': 'g4ad.8xlarge',
 'MemoryInfo': {'SizeInMiB': 131072},
 'ProcessorInfo': {'SupportedArchitectures': ['x86_64']},
 'VCpuInfo': {'DefaultCores': 16,
              'DefaultThreadsPerCore': 2,
              'DefaultVCpus': 32}}
```

2022-02-04 22:04 UTC, bblommers requested changes
Hi @edisongustavo, thanks for the PR! Would you mind adding a test case for this, to verify that the values are send through correctly? The test cases in `tests/test_ec2/test_instance_types.py` should be a good starting point

2022-02-07 08:48 UTC, edisongustavo commented
Hey @bblommers , sure I will work on that right on! Thanks for taking a look at the PR.

2022-02-07 09:29 UTC, edisongustavo commented
@bblommers , I have added a unit test where I `assert` on the entire result of `GpuInfo`, this way anything that gets added will have to be reflected in the test so that if people in the future improve the template, they also have to change the test.

If you think I shouldn't go this route and use the `.should...` statements, then I'll gladly rewrite the test.

2022-02-07 15:13 UTC, bblommers approved these changes
LGTM! Thanks for adding the test, @edisongustavo 👍

2022-02-07 15:13 UTC, merged