Add organizations close_account feature
spulec/moto pull request #5040
Opened 2022-04-19 15:25 UTC by donelupus

2022-04-19 20:33 UTC, bblommers requested changes
Hi @donelupus, thanks for the PR! Looks good overall, just got two minor comments

2022-04-20 05:19 UTC, donelupus commented on moto/organizations/models.py
> +                "CompletedTimestamp": unix_time(self.create_time),
Good point. I changed it accordingly.

2022-04-20 05:20 UTC, donelupus commented on moto/organizations/models.py
> +        raise AccountNotFoundException
I added one more test to check that the AccountNotFoundException is thrown.

2022-04-21 09:44 UTC, bblommers approved these changes
LGTM! Thanks for adding this feature @donelupus :+1:

2022-04-21 09:44 UTC, merged