Databrew: add recipe version support
spulec/moto pull request #5094
Opened 2022-05-04 10:45 UTC by michael-sanders

Adds recipe versioning to the databrew support.

This includes these additional methods:
* delete_recipe_version()
* list_recipe_versions()
* publish_recipe()

Also fixed exceptions raised by existing for recipe-related methods to match those in AWS documentation:
* RecipeAlreadyExistsException -> ConflictException
* RecipeNotFoundException -> ResourceNotFoundException

2022-05-04 12:01 UTC, michael-sanders commented
I believe that the unit test failure (https://github.com/spulec/moto/runs/6288585539?check_suite_focus=true) is not related to this change.

2022-05-05 11:05 UTC, bblommers requested changes

2022-05-05 15:40 UTC, michael-sanders commented on moto/databrew/models.py
> +            FakeRecipe.valid_version(recipe_version)
I've now changed it to check the result and throw an appropriate exception.

2022-05-05 20:33 UTC, bblommers approved these changes
LGTM! Thank you for the PR and the changes @michael-sanders

2022-05-05 20:33 UTC, merged