add authorizerPayloadFormatVersion to the authorizer
spulec/moto pull request #5144
Opened 2022-05-17 12:31 UTC by calvernaz

2022-05-17 14:25 UTC, bblommers requested changes
Would you mind adding a test for this? I know it's a small change, but it's always good to verify that it works correctly

2022-05-19 11:07 UTC, bblommers approved these changes
LGTM - thanks @calvernaz!

2022-05-19 11:07 UTC, merged

2022-09-11 13:43 UTC, bblommers commented
Hi @calvernaz, do you remember the usecase for this PR? I'm not able to reproduce this, i.e. creating a authorizer against AWS without version does no automatically assign one.
Does AWS add the version only for a specific parameter combination, maybe?

The request that I used:
```
{
    "authorizerType": "JWT",
    "identitySource": [
        "$request.header.Authorization"
    ],
    "jwtConfiguration": {
        "audience": [
            "sth"
        ],
        "issuer": "..."
    },
    "name": "testauth"
}
```

And response from AWS:
```
{
    "authorizerId": "..",
    "authorizerType": "JWT",
    "identitySource": [
        "$request.header.Authorization"
    ],
    "jwtConfiguration": {
        "audience": [
            "sth"
        ],
        "issuer": "..."
    },
    "name": "testauth"
}
```

The Terraform tests for `TestAccAPIGatewayV2Authorizer` also fail because of this change - they pass when I revert it.

2022-09-12 14:45 UTC, calvernaz commented
Hi @bblommers, so it should come from [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_authorizer#authorizer_payload_format_version), so it should be only available for v2 APIs. It's also available [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-authorizer.html) for CF.

I can't speak for why the terraform tests fail, but the setting is definitely there. 

The use case comes from the lambda authorizers input and output format. (https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html), 

> Hi @calvernaz, do you remember the usecase for this PR? I'm not able to reproduce this, i.e. creating a authorizer against AWS without version does no automatically assign one. Does AWS add the version only for a specific parameter combination, maybe?
> 
> The request that I used:
> 
> ```
> {
>     "authorizerType": "JWT",
>     "identitySource": [
>         "$request.header.Authorization"
>     ],
>     "jwtConfiguration": {
>         "audience": [
>             "sth"
>         ],
>         "issuer": "..."
>     },
>     "name": "testauth"
> }
> ```
> 
> And response from AWS:
> 
> ```
> {
>     "authorizerId": "..",
>     "authorizerType": "JWT",
>     "identitySource": [
>         "$request.header.Authorization"
>     ],
>     "jwtConfiguration": {
>         "audience": [
>             "sth"
>         ],
>         "issuer": "..."
>     },
>     "name": "testauth"
> }
> ```
> 
> The Terraform tests for `TestAccAPIGatewayV2Authorizer` also fail because of this change - they pass when I revert it.

2022-09-12 14:53 UTC, bblommers commented
The setting is definitely there, but I'm just curious at under which conditions it defaults to `2.0`. It doesn't always take that default value.

2022-09-12 16:48 UTC, calvernaz commented
> The setting is definitely there, but I'm just curious at under which conditions it defaults to `2.0`. It doesn't always take that default value.

My understanding is that it defaults to 2.0, for HTTP APIs, when there is no value. The documentation doesn't state that, but it says "if you need REST compatibility use 1.0". I think that's what serverless defaults to.

2022-09-14 21:21 UTC, bblommers commented
Not specifying this value for type=REQUEST actually throws an error. It's not stated in the documentation, but running this command:
```
aws apigatewayv2 create-authorizer --api-id ... --authorizer-type "REQUEST" --identity-source "" --name testauth2 --authorizer-uri "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:0000:function:test/invocations"
```
returns this error from AWS:
```
An error occurred (BadRequestException) when calling the CreateAuthorizer operation: AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer
```

So it will never default to anything. I'll try to create a PR shortly to mimic this error in Moto, and reverse the default value.

2022-09-14 21:33 UTC, calvernaz commented
> Not specifying this value for type=REQUEST actually throws an error. It's not stated in the documentation, but running this command:
> 
> ```
> aws apigatewayv2 create-authorizer --api-id ... --authorizer-type "REQUEST" --identity-source "" --name testauth2 --authorizer-uri "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:0000:function:test/invocations"
> ```
> 
> returns this error from AWS:
> 
> ```
> An error occurred (BadRequestException) when calling the CreateAuthorizer operation: AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer
> ```
> 
> So it will never default to anything. I'll try to create a PR shortly to mimic this error in Moto, and reverse the default value.

Thanks for getting to the bottom of this, clearly an oversight from my side.