fix template variable typo
spulec/moto pull request #5147
Opened 2022-05-17 18:12 UTC by radam9

The template variable name for the elbv2 healthcheck protocol is incorrect, which causes the healthcheck protocol in any api call response to always be an empty string.

2022-05-18 08:38 UTC, bblommers requested changes
Hi @radam9, would you mind adding a check for this in our tests?
Looks like we already have a few tests where we verify the creation works, so we only need to add a single assertion to verify that the protocol is returned correctly:
https://github.com/spulec/moto/blob/6ae0aa52728311158c4556ac38caffc717af21dc/tests/test_elbv2/test_elbv2_target_groups.py#L80

2022-05-18 19:27 UTC, radam9 commented
> Hi @radam9, would you mind adding a check for this in our tests? Looks like we already have a few tests where we verify the creation works, so we only need to add a single assertion to verify that the protocol is returned correctly:
> 
> https://github.com/spulec/moto/blob/6ae0aa52728311158c4556ac38caffc717af21dc/tests/test_elbv2/test_elbv2_target_groups.py#L80

Hey @bblommers,
I have added the test, but after committing I thought I would check to see if the test would fail if I revert my change, but that was not the case.
So in the tests `test_create_target_group_and_listeners()` and `test_modify_target_group()` for example, the `target_group` has the proper `HealthCheckProtocol` attribute even if I don't pass it as a parameter to the `create_target_group()` method.

2022-05-18 22:00 UTC, bblommers commented
@radam9 The `describe_target_groups`-function returns the value correctly, yes.
But the `create_target_group`-function does not return the value without your change.

2022-05-19 16:26 UTC, radam9 commented
That explains why the check didn't make any difference :)
I moved the check to the proper location in the test.

2022-05-19 17:35 UTC, bblommers approved these changes
LGTM! Thanks for the fix @radam9

2022-05-19 17:35 UTC, merged