Add keypair validation
spulec/moto pull request #5152
Opened 2022-05-20 15:11 UTC by szopen321

proposed fix for https://github.com/spulec/moto/issues/5151

2022-05-20 15:13 UTC, szopen321 commented
This PR is a WIP. 
I'm creating it to show my aproach and possibly change it according to your suggestions.

2022-05-21 10:34 UTC, bblommers requested changes
Thanks for the PR @szopen321! The approach looks good, just left a few comments

2022-05-21 10:34 UTC, bblommers commented on tests/test_ec2/test_ec2_integration.py
> +    ec2_client = boto3.client("ec2", region_name="us-east-1")
This client is already initialized two lines down

2022-05-21 10:34 UTC, bblommers commented on moto/ec2/models/instances.py
> +        describe_key_pairs(key_names=[kwargs.get("key_name")])
```suggestion
        self.describe_key_pairs(key_names=[kwargs.get("key_name")])
```
Minor nitpick - I don't think reassigning the method does anything for readability

2022-05-23 11:38 UTC, szopen321 commented
I have put keypair validation behind the flag as it can cause problems potentially.

2022-05-24 14:07 UTC, bblommers commented
> I have put keypair validation behind the flag as it can cause problems potentially.

That actually makes a lot of sense @szopen321.

Now that this validation is optional, we wouldn't need to change everything - existing tests can continue to use an invalid keypair. Would you mind changing the PR to only include he logic and the one new test, that validates that it breaks with the validation enabled?
I realize that it's a bit of extra work - feel free to just open a new branch/PR with only the required changes if that's easier.

2022-05-25 14:17 UTC, bblommers approved these changes
Awesome - thanks @szopen321!

2022-05-25 14:18 UTC, merged