Bug fix for selecting KMS key via alias ARN
spulec/moto pull request #5182
Opened 2022-06-01 07:29 UTC by BlueDragon23

When using Localstack with moto as the KMS provider, I encountered issues with selecting a key via the alias ARN. I believe this change fixes the issue by ensuring the `alias/` prefix is included when the name is extracted from the ARN. I've added tests to the KMS model to verify that, and that encryption works via all the other supported mechanisms

2022-06-02 21:17 UTC, bblommers requested changes
Hi @BlueDragon23, could you add another test using the boto3 SDK, to show what scenario is fixed with this change?

There are quite a few tests already in `tests/test_kms/test_kms_boto3`, so feel free to reuse or extend one of them.

2022-06-02 21:17 UTC, bblommers commented on tests/test_kms/test_model.py
> +    assert arn is not None
These assertions should be more specific. What is the format of the ARN that we're expecting?

(Same goes for all other tests)

2022-06-06 01:15 UTC, BlueDragon23 commented
Thanks for the feedback! I've updated the model tests to be more specific. It turns out there _was_ an existing test in `test_kms_boto3` that covered this use case, but it was always using the `key_id` instead of the `target_id`. I've changed that now, so it verifies the case of generating a data key using the alias ARN

2022-06-06 10:57 UTC, bblommers approved these changes
LGTM - thanks for the PR @BlueDragon23!

2022-06-06 10:57 UTC, merged