Stable cognito user pool
spulec/moto pull request #5194
Opened 2022-06-07 07:23 UTC by c0va23

Hi!

We create a Cogito UserPool before running integration tests, and random IDs complicate the process of finding a pool.

I added an environment variable `MOTO_COGNITO_IDP_USER_POOL_ID_STRATEGY=HASH`, setting which makes the ID of Cognito Userpool reproducible. I think this change will be useful to other moto users as well.

2022-06-07 21:03 UTC, bblommers requested changes
Hi @c0va23, thanks for the PR! This makes sense - I've just got some comments on the approach.

Would you mind adding a new test for this as well? Existing tests for `create_user_pool` can be found here: 
https://github.com/spulec/moto/blob/master/tests/test_cognitoidp/test_cognitoidp.py

See this test for an example on how to set environment variables for a single test:
https://github.com/spulec/moto/blob/master/tests/test_core/test_mock_regions.py#L27

Note the `if TEST_SERVER_MODE: skip` construct there - that is always necessary for tests that modify environment variables, as we cannot control them in ServerMode.

2022-06-09 06:55 UTC, c0va23 commented
@bblommers, I will correct all comments and suggestions. I will try to do it within the next couple of weeks.

2022-06-12 10:38 UTC, c0va23 commented
@bblommers , i fix all comments and add tests.

2022-06-12 16:28 UTC, bblommers approved these changes
Awesome - thanks again @c0va23!

2022-06-13 10:14 UTC, merged