fix attribute addition when updating thing groups
spulec/moto pull request #5318
Opened 2022-07-22 08:42 UTC by MrGreenTea

This fixes a bug when updating a thing group without attributes.

To reproduce it:

```py

client = boto3.client("iot")
# important: no thingGroupProperties here
client.create_thing_group(thingGroupName="example")
# will raise KeyError for "attributePayload"
client.update_thing_group(
    thingGroupName=name,
    thingGroupProperties={
        "attributePayload": {
            "attributes": {"example-attribute": "example-value"},
            "merge": False,
        }
    },
)
```

I also fixed a minor difference in behaviour. When a thing group is updated with an empty object for `"attributes"` AWS will simply ignore it and not add it to the properties.

2022-07-26 10:55 UTC, bblommers approved these changes

2022-07-27 10:07 UTC, bblommers requested changes
Same here actually @MrGreenTea - happy to merge once the conflicts are resolved

2022-07-27 10:19 UTC, MrGreenTea commented
done

2022-07-27 12:00 UTC, bblommers approved these changes
Nice one 👍

2022-07-27 12:01 UTC, merged