Fix KeyError on describe_db_clusters for non-existent cluster
spulec/moto pull request #5321
Opened 2022-07-22 14:16 UTC by t3hG04T

Throw the correct exception if the requested cluster does not exist. Fixes #5320

2022-07-24 20:04 UTC, t3hG04T commented
Added the missing test now, run black and linters according to the docs.

2022-07-26 10:12 UTC, bblommers requested changes
Hi @t3hG04T, would you mind merging in the latest master? That should fix the build

2022-07-26 16:08 UTC, t3hG04T commented
Hi @bblommers , synced and rebased, ready for testing.

2022-07-26 19:18 UTC, bblommers approved these changes
Awesome - thanks @t3hG04T!

2022-07-26 19:19 UTC, merged