DynamoDB: add check for empty key when getting an item (fix #5345)
spulec/moto pull request #5348
Opened 2022-07-30 23:15 UTC by ppena-LiveData

fix #5345 by making sure an exception is raised if a user is trying to get an item but providing an empty key

2022-08-01 19:58 UTC, ppena-LiveData commented
I'm confused. How could all the unit tests pass, which would include the `test_item_add_empty_key_exception()` test, but `Codecov` claim that the exception that the unit test tested for was not raised?

2022-08-02 10:37 UTC, MrGreenTea requested changes

2022-08-02 10:37 UTC, MrGreenTea commented on moto/dynamodb/responses.py
> +                "empty string value. Key: " + empty_keys[0]
```suggestion
                f"empty string value. Key: {empty_keys[0]}"
```

2022-08-02 10:37 UTC, MrGreenTea commented on tests/test_dynamodb/exceptions/test_key_length_exceptions.py
> +        "One or more parameter values were invalid: An AttributeValue may not contain an empty string"
This message is different than the one you raise:

```suggestion
        "One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value. Key: S"
```

2022-08-02 15:29 UTC, ppena-LiveData commented
Ooooh, I see my mistake! I'm sorry; it was a dumb copy and paste error. I forgot to change the test code I copied from calling `conn.put_item()` to calling `conn.get_item()`. It should be fixed with my latest commit.

2022-08-02 17:43 UTC, bblommers approved these changes
Nice one - thanks for fixing this @ppena-LiveData!

2022-08-02 17:43 UTC, merged