add rds enable_http_endpoint attribute
spulec/moto pull request #5470
Opened 2022-09-13 17:28 UTC by marshall7m

The current implementation of mocking the  RDS `CreateDBCluster` sets HttpEndpointEnabled to False by default without regard to an enable_http_endpoint parameter value. 

The PR introduces a `self.enable_http_endpoint` attribute within the `Cluster` class and simulates the conditional constraints the AWS API has for enabling HTTP endpoints. Specifically, the conditions relate to the desired engine, engine version, and engine_mode configurations for the cluster to be created.

2022-09-14 10:10 UTC, bblommers requested changes
Hi @marshall7m, thanks for the PR! Would you mind adding a few tests to verify this works correctly?

The existing tests reside in `tests/test_rds`, so you should be able to just extend those. Let me know if you need any help with that.

2022-09-15 00:26 UTC, marshall7m commented
> Hi @marshall7m, thanks for the PR! Would you mind adding a few tests to verify this works correctly?
> 
> The existing tests reside in `tests/test_rds`, so you should be able to just extend those. Let me know if you need any help with that.

Hi @bblommers, thanks for the quick response. I added the appropriate tests. Let me know if the input Engine, EngineMode, and EngineVersion should be parametrized within the tests for more coverage or if the current input is sufficient. I'll be glad to make the changes if needed.

2022-09-18 17:28 UTC, bblommers requested changes
Looks like the linter is failing @marshall7m - if we can remove the print-statement and get the build to pass I'd be happy to merge

2022-09-18 17:28 UTC, bblommers commented on moto/rds/models.py
> +        print(kwargs)
Please remove the print-statement

2022-09-18 19:59 UTC, marshall7m commented on moto/rds/models.py
> +        print(kwargs)
ooops, thanks!

2022-09-19 09:20 UTC, bblommers commented
The linter is still failing @marshall7m - see the CI here: https://github.com/spulec/moto/actions/runs/3078428258

You can run `make lint` locally to check as well.

2022-09-19 17:14 UTC, bblommers approved these changes
Nice one - thanks again for fixing this @marshall7m!

2022-09-19 17:14 UTC, merged

2022-09-20 00:38 UTC, marshall7m commented
> Nice one - thanks again for fixing this @marshall7m!

@bblommers No problem, thanks for the guidance along the way!