Fix error listing tags for rds db subnet group
spulec/moto pull request #5480
Opened 2022-09-16 12:15 UTC by szopen321

Suggested solution to https://github.com/spulec/moto/issues/5479

2022-09-16 16:03 UTC, bblommers requested changes
Would you mind adding a test for this @szopen321? As it stands I don't immediately see what error it would fix

Edit: I just realized you made it clear what's wrong in the original issue. Verification that this value is now returned properly would still be nice though :)

2022-09-16 16:03 UTC, bblommers commented on moto/rds/models.py
> +        self, subnet_name, description, subnets, tags, region, account_id
The region and account are already available in the backend, so we don't have to pass them explicitly.
`self.region_name` and `self.account_id` out the top of my head

2022-09-19 08:59 UTC, szopen321 commented
Oh, yes, my apologies! I've been meaning to mention aws docs to make the changes clearer.

This docs have information about arn missing:
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBSubnetGroups.html

While below it is included:
https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-subnet-groups.html
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBSubnetGroup.html

I used their feedback form in hopes they will complete the docs.

2022-09-20 11:42 UTC, bblommers approved these changes
Nice one - thanks for the fix @szopen321!

2022-09-20 11:42 UTC, merged