Add expression param to existing get_tables glue api
spulec/moto pull request #5495
Opened 2022-09-26 15:09 UTC by rafcio19

Currently [boto3 implements](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_tables) `glue.get_tables` with additional `Expression` parameter:

> Expression (string) -- A regular expression pattern. If present, only those tables whose names match the pattern are returned.

This is the implementation.

2022-09-27 07:59 UTC, rafcio19 commented
Hi @bblommers, thanks for approving the workflows. However, some of the TestTerraform ones fail and they look unrelated to my changes 🤷 
All I see in the logs is `Error:`
Are you able to see more?

2022-09-27 22:40 UTC, bblommers commented
Don't worry about the Terraform tests @rafcio19 - their 1.3.0 release broke quite a few things. Our tests should be fine again in 1.3.1, so we can ignore those failures for now

2022-09-27 22:46 UTC, bblommers requested changes

2022-09-27 22:46 UTC, bblommers commented on tests/test_glue/helpers.py
> +    return client.get_tables(DatabaseName=database_name, Expression=expression)
```suggestion
def get_tables(client, database_name, expression=None):
    if expression:
        return client.get_tables(DatabaseName=database_name, Expression=expression)
    else:
        return client.get_tables(DatabaseName=database_name)
```
Most of the tests do not provide an expression - and we should verify that it still works, even if an expression is not provided.

You may want to test this out locally, I expect some tests to fail with this change

2022-09-27 22:46 UTC, bblommers commented on moto/glue/models.py
> +            if bool(re.match(expression, table_name))
With the earlier change, the expression will sometimes be None. So we should make sure that we handle that appropriately.

Also: I don't think the `bool()` conversion is necessary here. `re.match()` will return a None-object if there is no match, so we can test against that

2022-09-27 22:46 UTC, bblommers commented on moto/glue/models.py
> +    def get_tables(self, database_name, expression=""):
```suggestion
    def get_tables(self, database_name, expression):
```
The `expression`-parameter is always provided by `responses.py` - we just have to ensure we can deal with a None-value

2022-09-28 10:43 UTC, bblommers approved these changes
Awesome - thanks for fixing this @rafcio19!

2022-09-28 10:44 UTC, merged

2022-10-04 13:45 UTC, robert-schmidtke commented
I am not sure this is the correct implementation. Glue's `get_tables` does accept a simple wildcard, e.g. `*`:

```python
>>> tables = glue.get_tables(DatabaseName="my_test_database", Expression="*")
>>> len(tables)
2
```

This does not work with the Python `re` backed implementation here.

2022-10-04 20:52 UTC, rafcio19 commented
Do you have examples @robert-schmidtke? I've only been able to verify `*` as a wildcard:

```
    import boto3
    glue = boto3.client('glue')
    glue.create_database(DatabaseInput={"Name": 'test'})
    glue.create_table(TableInput={"Name": "test123_table"}, DatabaseName='test')
    o = glue.get_tables(DatabaseName='test', Expression='test123_table')
    print([x['Name'] for x in o['TableList']])

    $ ['test123_table']

    o = glue.get_tables(DatabaseName='test', Expression='test1*table')
    print([x['Name'] for x in o['TableList']])

    $ ['test123_table']
```

but others like`?` for single character matching don't work:

```
    o = glue.get_tables(DatabaseName='test', Expression='test12?_table')
    print([x['Name'] for x in o['TableList']])

    $ []
```

2022-10-05 07:20 UTC, robert-schmidtke commented
Hey @rafcio19, thanks for taking the time to produce examples here. I think I can only make `?` work as part of a normal regular expression, not a glob pattern. You're right on this one. So maybe the `*` wildcard is indeed special. So maybe the only idea for a change that I have is, if the `Expression` `startswith` `*`, prepend a `.`? What do you think?

2022-10-05 07:32 UTC, robert-schmidtke commented
I actually found a case where it does not work:

```python
# no dot before last asterisk works
>>> o = glue.get_tables(DatabaseName='test', Expression='.*table*')
>>> print([x['Name'] for x in o['TableList']])
['test123_table']

# dot before last asterisk does not work
>>> o = glue.get_tables(DatabaseName='test', Expression='.*table.*')
>>> print([x['Name'] for x in o['TableList']])
[]
```

2022-10-05 07:56 UTC, rafcio19 commented
Hmm.. that last call `'.*table.*'` looks like a glue bug since the regex is valid. Prepending `*` with a `.`, if `*` is not the last character in the expression seems like a pragmatic way to tackle this, rather than trying to divine all the possible edge cases.

2022-10-05 11:28 UTC, robert-schmidtke commented
Would you be willing to open another PR for this? I would much appreciate it for sure :)

2022-10-05 21:29 UTC, bblommers commented
Thanks for raising this and investigating the AWS behaviour @robert-schmidtke!